-- Frozen catalog snapshot for the agreed historical estimate. Do not regenerate this migration.
ALTER TABLE users ADD COLUMN xp BIGINT NOT NULL DEFAULT 0 CHECK (xp >= 0);
CREATE TABLE card_acquisitions (
    id BIGSERIAL PRIMARY KEY,
    opening_id UUID NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    card_id TEXT NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    rarity TEXT,
    xp_each INTEGER NOT NULL DEFAULT 0 CHECK (xp_each >= 0),
    source TEXT NOT NULL,
    telegram_update_id BIGINT,
    received_at TIMESTAMPTZ, -- NULL for estimated baseline; never invent an acquisition time.
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (opening_id, card_id)
);
CREATE INDEX idx_card_acquisitions_user_time ON card_acquisitions(user_id, recorded_at DESC, id DESC);
CREATE INDEX idx_card_acquisitions_update ON card_acquisitions(telegram_update_id) WHERE telegram_update_id IS NOT NULL;
CREATE UNIQUE INDEX idx_card_acquisitions_draw_update ON card_acquisitions(source,telegram_update_id,card_id)
    WHERE source IN ('pack','free_card') AND telegram_update_id IS NOT NULL;
CREATE TABLE free_card_receipts (
    update_id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    card_id TEXT NOT NULL,
    is_new BOOLEAN NOT NULL,
    completed_collection_ids TEXT[] NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_free_card_receipts_user ON free_card_receipts(user_id, created_at DESC);
CREATE TEMP TABLE xp_catalog_snapshot (card_id TEXT PRIMARY KEY, rarity TEXT NOT NULL, xp_each INTEGER NOT NULL) ON COMMIT DROP;
INSERT INTO xp_catalog_snapshot VALUES
('sleepy', 'COMMON', 1),
('sock-thief', 'COMMON', 1),
('blanket-burrito', 'COMMON', 1),
('window-kitty', 'UNCOMMON', 2),
('yarn-keeper', 'UNCOMMON', 2),
('fireplace-friend', 'RARE', 3),
('pillow-fort', 'RARE', 3),
('tiny-gardener', 'EPIC', 5),
('boxie', 'LEGENDARY', 12),
('dreamweaver', 'MYTHIC', 8),
('sunny', 'COMMON', 1),
('windy', 'COMMON', 1),
('snowy', 'COMMON', 1),
('blossom', 'UNCOMMON', 2),
('cloudy', 'UNCOMMON', 2),
('rainy', 'RARE', 3),
('first-snow', 'RARE', 3),
('thunder', 'EPIC', 5),
('rainbow-chaser', 'EPIC', 5),
('storm-keeper', 'LEGENDARY', 12),
('aurora', 'MYTHIC', 8),
('reader', 'COMMON', 1),
('napper', 'COMMON', 1),
('gamer', 'COMMON', 1),
('fisher', 'UNCOMMON', 2),
('painter', 'UNCOMMON', 2),
('knitter', 'UNCOMMON', 2),
('photographer', 'RARE', 3),
('skater', 'RARE', 3),
('pianist', 'EPIC', 5),
('treasure-hunter', 'EPIC', 5),
('master-collector', 'LEGENDARY', 12),
('dream-painter', 'MYTHIC', 8),
('barista', 'COMMON', 1),
('postcat', 'COMMON', 1),
('florist', 'COMMON', 1),
('gardener', 'UNCOMMON', 2),
('mechanic', 'UNCOMMON', 2),
('chef', 'UNCOMMON', 2),
('doctor', 'RARE', 3),
('detective', 'RARE', 3),
('firefighter', 'EPIC', 5),
('lighthouse-keeper', 'EPIC', 5),
('baker', 'EPIC', 5),
('librarian', 'EPIC', 5),
('clockmaker', 'MYTHIC', 8),
('tailor', 'COMMON', 1),
('teacher', 'COMMON', 1),
('carpenter', 'UNCOMMON', 2),
('veterinarian', 'UNCOMMON', 2),
('scientist', 'RARE', 3),
('conductor', 'EPIC', 5),
('royal-architect', 'LEGENDARY', 12),
('city-bus', 'COMMON', 1),
('red-tram', 'COMMON', 1),
('cargo-bike', 'COMMON', 1),
('harbor-tug', 'COMMON', 1),
('taxi-cab', 'UNCOMMON', 2),
('river-ferry', 'UNCOMMON', 2),
('alpine-cable-car', 'UNCOMMON', 2),
('seaplane', 'RARE', 3),
('rescue-helicopter', 'RARE', 3),
('desert-convoy', 'RARE', 3),
('night-express', 'EPIC', 5),
('ocean-liner', 'EPIC', 5),
('sky-cruiser', 'LEGENDARY', 12),
('starship-ark', 'MYTHIC', 8),
('backpacker', 'COMMON', 1),
('camper', 'COMMON', 1),
('tourist', 'COMMON', 1),
('hitchhiker', 'UNCOMMON', 2),
('sailor', 'UNCOMMON', 2),
('train-rider', 'UNCOMMON', 2),
('mountain-climber', 'RARE', 3),
('desert-traveler', 'RARE', 3),
('balloonist', 'EPIC', 5),
('polar-explorer', 'EPIC', 5),
('wanderer', 'LEGENDARY', 12),
('worldwalker', 'MYTHIC', 8),
('stargazer', 'COMMON', 1),
('moon-dreamer', 'COMMON', 1),
('telescope-kitty', 'COMMON', 1),
('rocket-cadet', 'UNCOMMON', 2),
('moonwalker', 'UNCOMMON', 2),
('satellite-cat', 'RARE', 3),
('comet-chaser', 'RARE', 3),
('astronaut', 'EPIC', 5),
('mars-explorer', 'EPIC', 5),
('star-captain', 'LEGENDARY', 12),
('cosmic-guardian', 'MYTHIC', 8),
('late-walker', 'COMMON', 1),
('window-light', 'COMMON', 1),
('alley-cat', 'COMMON', 1),
('lamplighter', 'UNCOMMON', 2),
('rooftop-kitty', 'UNCOMMON', 2),
('night-watcher', 'RARE', 3),
('midnight-cafe', 'RARE', 3),
('neon-rider', 'EPIC', 5),
('moonlight-musician', 'EPIC', 5),
('keeper-of-lights', 'LEGENDARY', 12),
('midnight-king', 'MYTHIC', 8),
('cookie', 'COMMON', 1),
('milk-lover', 'COMMON', 1),
('pancake', 'COMMON', 1),
('donut', 'COMMON', 1),
('hot-cocoa', 'UNCOMMON', 2),
('ramen', 'UNCOMMON', 2),
('strawberry', 'UNCOMMON', 2),
('sushi', 'RARE', 3),
('bubble-tea', 'RARE', 3),
('afternoon-tea', 'RARE', 3),
('candy-maker', 'EPIC', 5),
('midnight-ramen', 'EPIC', 5),
('royal-feast', 'EPIC', 5),
('ambrosia', 'MYTHIC', 8),
('muffin', 'COMMON', 1),
('cheese-board', 'COMMON', 1),
('apple-pie', 'UNCOMMON', 2),
('matcha-parfait', 'RARE', 3),
('moonlight-fondue', 'EPIC', 5),
('golden-honey', 'LEGENDARY', 12),
('runner', 'COMMON', 1),
('tennis-kitty', 'COMMON', 1),
('swimmer', 'COMMON', 1),
('yoga-kitty', 'COMMON', 1),
('skateboarder', 'UNCOMMON', 2),
('gymnast', 'UNCOMMON', 2),
('cyclist', 'UNCOMMON', 2),
('table-tennis-duo', 'UNCOMMON', 2),
('ice-skater', 'RARE', 3),
('rock-climber', 'RARE', 3),
('rowing-crew', 'RARE', 3),
('soccer-squad', 'EPIC', 5),
('basketball-buddies', 'EPIC', 5),
('hockey-team', 'EPIC', 5),
('grand-champion', 'LEGENDARY', 12),
('sports-star', 'MYTHIC', 8),
('january', 'COMMON', 1),
('february', 'UNCOMMON', 2),
('march', 'RARE', 3),
('april', 'COMMON', 1),
('may', 'UNCOMMON', 2),
('june', 'RARE', 3),
('july', 'COMMON', 1),
('august', 'UNCOMMON', 2),
('september', 'RARE', 3),
('october', 'COMMON', 1),
('november', 'UNCOMMON', 2),
('december', 'RARE', 3),
('season-winter', 'EPIC', 5),
('season-spring', 'EPIC', 5),
('season-summer', 'LEGENDARY', 12),
('season-autumn', 'MYTHIC', 8),
('tea-party-pals', 'COMMON', 1),
('puzzle-partners', 'COMMON', 1),
('garden-helpers', 'COMMON', 1),
('story-circle', 'COMMON', 1),
('baking-buddies', 'UNCOMMON', 2),
('movie-night-crew', 'UNCOMMON', 2),
('picnic-pals', 'UNCOMMON', 2),
('art-club', 'RARE', 3),
('music-jam', 'RARE', 3),
('lantern-makers', 'EPIC', 5),
('treehouse-gang', 'LEGENDARY', 12),
('friendship-festival', 'MYTHIC', 8),
('europe-belarus', 'COMMON', 1),
('europe-belgium', 'COMMON', 1),
('europe-denmark', 'COMMON', 1),
('europe-netherlands', 'COMMON', 1),
('europe-czechia', 'COMMON', 1),
('europe-hungary', 'COMMON', 1),
('europe-poland', 'COMMON', 1),
('europe-finland', 'COMMON', 1),
('europe-estonia', 'COMMON', 1),
('europe-serbia', 'UNCOMMON', 2),
('europe-germany', 'UNCOMMON', 2),
('europe-austria', 'UNCOMMON', 2),
('europe-portugal', 'UNCOMMON', 2),
('europe-croatia', 'UNCOMMON', 2),
('europe-romania', 'UNCOMMON', 2),
('europe-sweden', 'UNCOMMON', 2),
('europe-united-kingdom', 'UNCOMMON', 2),
('europe-armenia', 'RARE', 3),
('europe-georgia', 'RARE', 3),
('europe-spain', 'RARE', 3),
('europe-switzerland', 'RARE', 3),
('europe-ireland', 'RARE', 3),
('europe-france', 'RARE', 3),
('europe-ukraine', 'RARE', 3),
('europe-greece', 'EPIC', 5),
('europe-italy', 'EPIC', 5),
('europe-norway', 'EPIC', 5),
('europe-russia', 'EPIC', 5),
('europe-iceland', 'LEGENDARY', 12),
('europe-turkey', 'MYTHIC', 8),
('asia-bangladesh', 'COMMON', 1),
('asia-pakistan', 'COMMON', 1),
('asia-malaysia', 'COMMON', 1),
('asia-singapore', 'COMMON', 1),
('asia-philippines', 'COMMON', 1),
('asia-cambodia', 'COMMON', 1),
('asia-laos', 'COMMON', 1),
('asia-qatar', 'COMMON', 1),
('asia-south-korea', 'COMMON', 1),
('asia-kazakhstan', 'UNCOMMON', 2),
('asia-uzbekistan', 'UNCOMMON', 2),
('asia-kyrgyzstan', 'UNCOMMON', 2),
('asia-tajikistan', 'UNCOMMON', 2),
('asia-vietnam', 'UNCOMMON', 2),
('asia-thailand', 'UNCOMMON', 2),
('asia-united-arab-emirates', 'UNCOMMON', 2),
('asia-oman', 'UNCOMMON', 2),
('asia-nepal', 'RARE', 3),
('asia-bhutan', 'RARE', 3),
('asia-sri-lanka', 'RARE', 3),
('asia-mongolia', 'RARE', 3),
('asia-iran', 'RARE', 3),
('asia-jordan', 'RARE', 3),
('asia-saudi-arabia', 'RARE', 3),
('asia-china', 'EPIC', 5),
('asia-india', 'EPIC', 5),
('asia-australia', 'EPIC', 5),
('asia-indonesia', 'EPIC', 5),
('asia-myanmar', 'LEGENDARY', 12),
('asia-japan', 'MYTHIC', 8),
('africa-ghana', 'COMMON', 1),
('africa-uganda', 'COMMON', 1),
('africa-rwanda', 'COMMON', 1),
('africa-malawi', 'COMMON', 1),
('africa-zambia', 'COMMON', 1),
('africa-senegal', 'COMMON', 1),
('africa-cameroon', 'COMMON', 1),
('africa-gabon', 'COMMON', 1),
('africa-cape-verde', 'COMMON', 1),
('africa-algeria', 'UNCOMMON', 2),
('africa-tunisia', 'UNCOMMON', 2),
('africa-nigeria', 'UNCOMMON', 2),
('africa-botswana', 'UNCOMMON', 2),
('africa-zimbabwe', 'UNCOMMON', 2),
('africa-mozambique', 'UNCOMMON', 2),
('africa-angola', 'UNCOMMON', 2),
('africa-cote-divoire', 'UNCOMMON', 2),
('africa-ethiopia', 'RARE', 3),
('africa-kenya', 'RARE', 3),
('africa-tanzania', 'RARE', 3),
('africa-namibia', 'RARE', 3),
('africa-mauritius', 'RARE', 3),
('africa-seychelles', 'RARE', 3),
('africa-sudan', 'RARE', 3),
('africa-morocco', 'EPIC', 5),
('africa-south-africa', 'EPIC', 5),
('africa-madagascar', 'EPIC', 5),
('africa-dr-congo', 'EPIC', 5),
('africa-mali', 'LEGENDARY', 12),
('africa-egypt', 'MYTHIC', 8),
('americas-belize', 'COMMON', 1),
('americas-honduras', 'COMMON', 1),
('americas-el-salvador', 'COMMON', 1),
('americas-nicaragua', 'COMMON', 1),
('americas-bahamas', 'COMMON', 1),
('americas-barbados', 'COMMON', 1),
('americas-guyana', 'COMMON', 1),
('americas-suriname', 'COMMON', 1),
('americas-uruguay', 'COMMON', 1),
('americas-guatemala', 'UNCOMMON', 2),
('americas-costa-rica', 'UNCOMMON', 2),
('americas-panama', 'UNCOMMON', 2),
('americas-dominican-republic', 'UNCOMMON', 2),
('americas-jamaica', 'UNCOMMON', 2),
('americas-haiti', 'UNCOMMON', 2),
('americas-trinidad-and-tobago', 'UNCOMMON', 2),
('americas-paraguay', 'UNCOMMON', 2),
('americas-canada', 'RARE', 3),
('americas-colombia', 'RARE', 3),
('americas-venezuela', 'RARE', 3),
('americas-ecuador', 'RARE', 3),
('americas-bolivia', 'RARE', 3),
('americas-cuba', 'RARE', 3),
('americas-grenada', 'RARE', 3),
('americas-united-states', 'EPIC', 5),
('americas-mexico', 'EPIC', 5),
('americas-peru', 'EPIC', 5),
('americas-chile', 'EPIC', 5),
('americas-argentina', 'LEGENDARY', 12),
('americas-brazil', 'MYTHIC', 8),
('halloween-candy-sorter', 'COMMON', 1),
('halloween-paper-bats', 'COMMON', 1),
('halloween-sheet-ghost', 'COMMON', 1),
('halloween-pumpkin-carver', 'COMMON', 1),
('halloween-costume-stitcher', 'COMMON', 1),
('halloween-window-webs', 'COMMON', 1),
('halloween-witch-hat', 'UNCOMMON', 2),
('halloween-vampire-cape', 'UNCOMMON', 2),
('halloween-pumpkin-garland', 'UNCOMMON', 2),
('halloween-treat-basket', 'UNCOMMON', 2),
('halloween-bat-wings', 'UNCOMMON', 2),
('halloween-lantern-path', 'RARE', 3),
('halloween-mummy-wrap', 'RARE', 3),
('halloween-cookie-decorator', 'RARE', 3),
('halloween-scarecrow-pal', 'RARE', 3),
('halloween-dragon-costume', 'EPIC', 5),
('halloween-shadow-theatre', 'EPIC', 5),
('halloween-haunted-cottage', 'EPIC', 5),
('halloween-masquerade-host', 'LEGENDARY', 12),
('halloween-midnight-parade', 'MYTHIC', 8),
('potion-maker', 'COMMON', 1),
('mushroom-picker', 'COMMON', 1),
('tower-princess', 'COMMON', 1),
('breadcrumb-trail', 'COMMON', 1),
('acorn-messenger', 'COMMON', 1),
('gingerbread-builder', 'COMMON', 1),
('well-listener', 'COMMON', 1),
('forest-witch', 'UNCOMMON', 2),
('little-knight', 'UNCOMMON', 2),
('lantern-fairy', 'UNCOMMON', 2),
('bridge-troll', 'UNCOMMON', 2),
('cloak-stitcher', 'UNCOMMON', 2),
('mirror-messenger', 'UNCOMMON', 2),
('spell-restorer', 'RARE', 3),
('fairy-healer', 'RARE', 3),
('story-spinner', 'RARE', 3),
('dream-door', 'RARE', 3),
('crystal-wayfinder', 'RARE', 3),
('dragon-rider', 'EPIC', 5),
('puppet-enchanter', 'EPIC', 5),
('cloud-castle-keeper', 'EPIC', 5),
('phoenix-nursery', 'EPIC', 5),
('wish-granter', 'LEGENDARY', 12),
('enchanted-king', 'MYTHIC', 8),
('tide-pool-kitty', 'COMMON', 1),
('seashell-collector', 'COMMON', 1),
('bubble-rider', 'COMMON', 1),
('sandcastle-architect', 'COMMON', 1),
('hermit-helper', 'COMMON', 1),
('anemone-neighbor', 'COMMON', 1),
('reef-mosaic', 'COMMON', 1),
('pearl-diver', 'UNCOMMON', 2),
('kelp-forest-scout', 'UNCOMMON', 2),
('seahorse-courier', 'UNCOMMON', 2),
('octopus-puzzle', 'UNCOMMON', 2),
('sponge-house', 'UNCOMMON', 2),
('reef-nurse', 'UNCOMMON', 2),
('shipwreck-explorer', 'RARE', 3),
('jellyfish-dancer', 'RARE', 3),
('manta-glider', 'RARE', 3),
('glow-cave-explorer', 'RARE', 3),
('reef-archivist', 'RARE', 3),
('coral-guardian', 'EPIC', 5),
('submarine-captain', 'EPIC', 5),
('lost-bell-keeper', 'EPIC', 5),
('ocean-tea-party', 'EPIC', 5),
('leviathan-whisperer', 'LEGENDARY', 12),
('abyss-monarch', 'MYTHIC', 8),
('street-guitarist', 'COMMON', 1),
('tambourine-kitten', 'COMMON', 1),
('music-box', 'COMMON', 1),
('triangle-player', 'COMMON', 1),
('tap-dancer', 'COMMON', 1),
('record-spinner', 'COMMON', 1),
('jazz-cat', 'UNCOMMON', 2),
('violin-dreamer', 'UNCOMMON', 2),
('accordion-waltz', 'UNCOMMON', 2),
('handpan-rain', 'UNCOMMON', 2),
('rhythm-workshop', 'UNCOMMON', 2),
('prima-ballerina', 'RARE', 3),
('flamenco-rose', 'RARE', 3),
('a-cappella', 'RARE', 3),
('ribbon-dancer', 'RARE', 3),
('opera-diva', 'EPIC', 5),
('northern-piper', 'EPIC', 5),
('stage-drummer', 'EPIC', 5),
('symphony-composer', 'LEGENDARY', 12),
('celestial-harmonist', 'MYTHIC', 8),
('seedling-planter', 'COMMON', 1),
('watering-helper', 'COMMON', 1),
('worm-friend', 'COMMON', 1),
('carrot-harvester', 'COMMON', 1),
('compost-helper', 'COMMON', 1),
('leaf-sweeper', 'COMMON', 1),
('strawberry-guardian', 'UNCOMMON', 2),
('butterfly-host', 'UNCOMMON', 2),
('bee-hotel-builder', 'UNCOMMON', 2),
('trellis-weaver', 'UNCOMMON', 2),
('apple-grafter', 'UNCOMMON', 2),
('pumpkin-grower', 'RARE', 3),
('rose-keeper', 'RARE', 3),
('bonsai-shaper', 'RARE', 3),
('lily-pond-watcher', 'RARE', 3),
('sunflower-giant', 'EPIC', 5),
('greenhouse-wizard', 'EPIC', 5),
('rain-garden-keeper', 'EPIC', 5),
('ancient-tree-keeper', 'LEGENDARY', 12),
('garden-of-dreams', 'MYTHIC', 8);
CREATE TEMP TABLE xp_holdings ON COMMIT DROP AS
SELECT user_id, card_id, SUM(quantity)::BIGINT AS quantity FROM (
    SELECT user_id, card_id, quantity FROM user_cards
    UNION ALL SELECT seller_id, card_id, 1 FROM market_listings WHERE status = 'ACTIVE'
    UNION ALL SELECT user_id, card_id, 1 FROM random_trade_pool WHERE status = 'WAITING'
) h GROUP BY user_id, card_id;
CREATE TEMP TABLE xp_receipt_counts ON COMMIT DROP AS
SELECT r.user_id, c.card_id, COUNT(*)::BIGINT AS quantity
FROM pack_opening_receipts r CROSS JOIN LATERAL unnest(r.card_ids) c(card_id)
GROUP BY r.user_id, c.card_id;
DO $$ BEGIN
    IF EXISTS (
        SELECT card_id FROM (SELECT card_id FROM xp_holdings UNION SELECT card_id FROM xp_receipt_counts) ids
        WHERE NOT EXISTS (SELECT 1 FROM xp_catalog_snapshot c WHERE c.card_id = ids.card_id)
    ) THEN RAISE EXCEPTION 'XP backfill contains a card absent from the frozen catalog'; END IF;
END $$;
-- Each surviving pack receipt is an exact historical draw; refunds do not remove it.
INSERT INTO card_acquisitions(opening_id,user_id,card_id,quantity,rarity,xp_each,source,telegram_update_id,received_at)
SELECT md5('legacy_pack:' || r.update_id::TEXT)::UUID, r.user_id, c.card_id, COUNT(*)::INTEGER, s.rarity, s.xp_each,
       'legacy_pack', r.update_id, r.created_at
FROM pack_opening_receipts r CROSS JOIN LATERAL unnest(r.card_ids) c(card_id)
JOIN xp_catalog_snapshot s ON s.card_id = c.card_id
GROUP BY r.update_id,r.user_id,r.created_at,c.card_id,s.rarity,s.xp_each;
-- Per card: max(known pack draws, surviving holdings including escrow), avoiding double counting.
INSERT INTO card_acquisitions(opening_id,user_id,card_id,quantity,rarity,xp_each,source,received_at)
SELECT gen_random_uuid(), h.user_id, h.card_id, (h.quantity - COALESCE(r.quantity,0))::INTEGER,
       s.rarity, s.xp_each, 'legacy_baseline', NULL
FROM xp_holdings h JOIN xp_catalog_snapshot s ON s.card_id = h.card_id
LEFT JOIN xp_receipt_counts r ON r.user_id = h.user_id AND r.card_id = h.card_id
WHERE h.quantity > COALESCE(r.quantity,0);
UPDATE users u SET xp = a.xp FROM (
    SELECT user_id, SUM(quantity::BIGINT * xp_each) AS xp FROM card_acquisitions GROUP BY user_id
) a WHERE u.id = a.user_id;
